name: Test
on: push
jobs:
  unit-test:
    runs-on: ubuntu-20.04
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
        - '2.6.8'
        - '2.7.5'
        - '3.0.5'
        - '3.1.3'
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rake
